version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "minha-carteira-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ehvhcuwlfano"
s3_prefix = "minha-carteira-stack"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
