AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  minha-carteira

  Sample SAM Template for minha-carteira


Parameters:
  LogLevel:
    Type: String
    Description: Application log level
    Default: INFO
    AllowedValues:
      - DEBUG
      - INFO
      - WARNING
      - ERROR
      - CRITICAL

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        LOG_LEVEL: !Ref LogLevel

Resources:

# DB
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName : 'minha-carteira-user'
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

# API
  MinhaCarteiraApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: s3://minha-carteira-bucket/api/swagger.yaml

      Auth:
        # DefaultAuthorizer: MyLambdaTokenAuthorizer
        # Authorizers:
        #   MyLambdaTokenAuthorizer:
        #     FunctionArn: !GetAtt UserLoginFunction.Arn
        ResourcePolicy:
            CustomStatements:
              [
                {
                    "Effect": "Allow",
                    "Principal": "*",
                    "Action": "execute-api:Invoke",
                    "Resource": "*"
                }
            ]

# Layers
  CommonFileLayers:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: CommonFileLayers
      Description: Python3.8 utility functions -- {common}
      RetentionPolicy: Delete
      ContentUri: layers/common-layer/package.zip
      CompatibleRuntimes:
        - python3.8

  YahooFinanceLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: YahooFinanceLayer
      Description: Python3.8 Yahoo Finance Layer -- {yfinance, requests, pandas}
      RetentionPolicy: Delete
      ContentUri: layers/yf-layer
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8              # Required to have AWS SAM build this layer

# Functions
  WalletNowFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: wallet-now/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Layers:
        - !Ref CommonFileLayers
        - !Ref YahooFinanceLayer
      Events:
        WalletNow:
          Type: Api
          Properties:
            Path: /wallet/now
            Method: post
            RestApiId:
              Ref: MinhaCarteiraApi

  UserCrudFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: user-crud/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Layers:
        - !Ref CommonFileLayers
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /user
            Method: post
            RestApiId:
              Ref: MinhaCarteiraApi
        GetUser:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: get
            RestApiId:
              Ref: MinhaCarteiraApi
        UpdateUser:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: put
            RestApiId:
              Ref: MinhaCarteiraApi
        DeleteUser:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: delete
            RestApiId:
              Ref: MinhaCarteiraApi

Outputs:
  # MinhaCarteiraApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MinhaCarteiraApi:
    Description: "API Gateway endpoint URL for Prod stage for Stock Price function"
    Value: !Sub "https://${MinhaCarteiraApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"


  WalletNowFunction:
    Description: "Get a Wallet current value Lambda Function ARN"
    Value: !GetAtt WalletNowFunction.Arn
  UserCrudFunction:
    Description: "Get a Wallet current value Lambda Function ARN"
    Value: !GetAtt UserCrudFunction.Arn

  WalletNowFunctionIamRole:
    Description: "Implicit IAM Role created for Stock Price function"
    Value: !GetAtt WalletNowFunctionRole.Arn
  UserCrudFunctionIamRole:
    Description: "Implicit IAM Role created for Stock Price function"
    Value: !GetAtt UserCrudFunctionRole.Arn